export type ProcedureShareProtectionDraft = {
  stake?: string;
  odd?: string;
  side?: "back" | "lay";
  layOdd?: string;
  commission?: string;
  increase?: string;
  cashback?: string;
  freebet?: boolean;
};

export type ProcedureShareEntryDetail = {
  scope: "sports" | "freebet_collection" | "freebet_conversion";
  role: "principal" | "protecao";
  order: number;
  resultKey: string;
  house?: string;
  value?: number;
  odd?: number;
  side?: "back" | "lay";
  layOdd?: number;
  commission?: number;
  increase?: number;
  cashback?: number;
  freebet?: boolean;
  operationDate?: string;
};

export type ProcedureShareResultDetail = {
  scope: "sports" | "freebet_collection" | "freebet_conversion";
  resultKey: string;
};

export type ProcedureShareValues = {
  version?: 1;
  procedureType?: string;
  operationDate?: string;
  game?: string;
  collectionGame?: string;
  conversionGame?: string;
  conversionBatchId?: string;
  houses?: string;
  entryValue?: number;
  note?: string;
  hitDouble?: boolean;
  doubleValue?: number;
  freebetHouse?: string;
  freebetValue?: number;
  freebetCondition?: string;
  procedureStatus?: "Pendente" | "Concluído";
  selectedHouses?: string[];
  collectionHouses?: string[];
  selectedFreebetHouse?: string;
  primaryStake?: string;
  primaryOdd?: string;
  primarySide?: "back" | "lay";
  primaryLayOdd?: string;
  primaryCommission?: string;
  primaryIncrease?: string;
  primaryCashback?: string;
  primaryFreebet?: boolean;
  sportProtections?: ProcedureShareProtectionDraft[];
  sportResultSelections?: string[];
  collectionPrimaryStake?: string;
  collectionPrimaryOdd?: string;
  collectionPrimarySide?: "back" | "lay";
  collectionPrimaryLayOdd?: string;
  collectionPrimaryCommission?: string;
  collectionPrimaryIncrease?: string;
  collectionPrimaryCashback?: string;
  collectionPrimaryFreebet?: boolean;
  collectionProtections?: ProcedureShareProtectionDraft[];
  collectionResultSelections?: string[];
  collectionDate?: string;
  conversionDate?: string;
  freebetCollectionOpen?: boolean;
  freebetConversionOpen?: boolean;
  freebetVisibleScope?: "all" | "collection" | "conversion";
  originIds?: number[];
  procedureEntries?: ProcedureShareEntryDetail[];
  procedureResults?: ProcedureShareResultDetail[];
};
