INSERT INTO casas_de_apostas (nome, saldo) 
VALUES 
  ('Betano', 0),
  ('Bet365', 0),
  ('Sportingbet', 0),
  ('Betfair', 0),
  ('Pinnacle', 0),
  ('EstrelaBet', 0),
  ('Superbet', 0),
  ('Novibet', 0),
  ('KTO', 0),
  ('Mc Games', 0),
  ('BetVip', 0),
  ('1xBet', 0),
  ('F12.Bet', 0),
  ('Esportes da Sorte', 0),
  ('Stake', 0),
  ('Betway', 0),
  ('Pixbet', 0),
  ('Meridianbet', 0),
  ('Vai de Bet', 0),
  ('Betsson', 0),
  ('Vbet', 0),
  ('Sorte na Bet', 0),
  ('FullBet', 0),
  ('Bolsa de Apostas', 0),
  ('Matchbook', 0),
  ('Bet Pix 365', 0),
  ('Betbra', 0),
  ('Lottu', 0),
  ('Aposta Bet', 0),
  ('Esportiva Bet', 0),
  ('Betesporte', 0),
  ('Betsul', 0),
  ('Betnacional', 0),
  ('Onabet', 0),
  ('Sporty Bet', 0),
  ('Betboo', 0),
  ('Lotogreen', 0),
  ('Br4bet', 0),
  ('Gol de Bet', 0),
  ('7k Bet', 0),
  ('Brasil Bet', 0),
  ('Bet da Sorte', 0),
  ('Casa de Apostas', 0),
  ('Multibet', 0),
  ('Jogo de ouro', 0),
  ('Betão', 0),
  ('R7 Bet', 0),
  ('4Win', 0 ),
  ('4play', 0),
  ('Pagou Bet', 0),
  ('Betou Bet', 0),
  ('Versus Bet', 0),
  ('Galera Bet', 0)

ON CONFLICT (nome) DO NOTHING;