INSERT INTO casas_de_apostas (nome, saldo) 
VALUES 
('10Game', 0),
  ('1Pra1', 0),
  ('1xBet', 0),
  ('20Bet', 0),
  ('22Bet', 0),
  ('4Play', 0),
  ('4Win', 0),
  ('6R', 0),
  ('7Games', 0),
  ('9D', 0),
  ('9F', 0),
  ('A247', 0),
  ('Afun', 0),
  ('Alfabet', 0),
  ('Aposta Ganha', 0),
  ('Aposta Online', 0),
  ('Aposta1', 0),
  ('Apostabet', 0),
  ('Apostamax', 0),
  ('Apostar', 0),
  ('Apostefacil', 0),
  ('Apostou', 0),
  ('Aviao', 0),
  ('B1Bet', 0),
  ('B2xBet', 0),
  ('Bandbet', 0),
  ('Bateubet', 0),
  ('Bc.Game', 0),
  ('Bellabet', 0),
  ('Bet da Sorte', 0),
  ('Bet do Milhão', 0),
  ('Bet.App', 0),
  ('Bet.Bet', 0),
  ('Bet365', 0),
  ('Bet4', 0),
  ('Bet7k', 0),
  ('Betagora', 0),
  ('Betaki', 0),
  ('Betano', 0),
  ('Betão', 0),
  ('Betboo', 0),
  ('Betboom', 0),
  ('Betbra', 0),
  ('Betespecial', 0),
  ('Betesporte', 0),
  ('Betfair', 0),
  ('Betfalcons', 0),
  ('Betfast', 0),
  ('Betfusion', 0),
  ('Betgorillas', 0),
  ('Betmaster', 0),
  ('BetMGM', 0),
  ('Betmotion', 0),
  ('Betnacional', 0),
  ('Betou Bet', 0),
  ('Betpark', 0),
  ('Betpix365', 0),
  ('Betsson', 0),
  ('Betsul', 0),
  ('BetVip', 0),
  ('Betwarrior', 0),
  ('Betwinner', 0),
  ('Big Bet', 0),
  ('Blaze', 0),
  ('Bolsa de Aposta', 0),
  ('Br4bet', 0),
  ('Brasil Bet', 0),
  ('Brasil da Sorte', 0),
  ('Bravobet', 0),
  ('Brazino777', 0),
  ('Brbet', 0),
  ('Brx', 0),
  ('Bullsbet', 0),
  ('Casa de Apostas', 0),
  ('Cassino Bet', 0),
  ('Cbesportes', 0),
  ('Cgg Bet', 0),
  ('Claze', 0),
  ('Dafabet', 0),
  ('Donaldbet', 0),
  ('Donos da Bola', 0),
  ('Energia', 0),
  ('Esporte365', 0),
  ('Esportes da Sorte', 0),
  ('Esportiva Bet', 0),
  ('Esportiva Vip', 0),
  ('EstrelaBet', 0),
  ('F12', 0),
  ('Fanbit', 0),
  ('Faz1Bet', 0),
  ('Fazobet', 0),
  ('Fg6', 0),
  ('Fogo777', 0),
  ('Fulltbet', 0),
  ('Galera Bet', 0),
  ('Ganhei', 0),
  ('Geralbet', 0),
  ('Gingabet', 0),
  ('Gol de Bet', 0),
  ('H2Bet', 0),
  ('Hanzbet', 0),
  ('Hiperbet', 0),
  ('iJogo', 0),
  ('Jogão', 0),
  ('Jogo de Ouro', 0),
  ('Jonbet', 0),
  ('Kingpanda', 0),
  ('KTO', 0),
  ('Lance de Sorte', 0),
  ('Leon.Bet', 0),
  ('LeoVegas', 0),
  ('Liderbet', 0),
  ('Lotogreen', 0),
  ('Lottoland', 0),
  ('Lottu', 0),
  ('Luckbet', 0),
  ('Luvabet', 0),
  ('Marjosports', 0),
  ('Matchbook', 0),
  ('Maximabet', 0),
  ('McGames', 0),
  ('Melbet', 0),
  ('Meridianbet', 0),
  ('Metgol', 0),
  ('Mmabet', 0),
  ('Mr.Jack.Bet', 0),
  ('Multibet', 0),
  ('Nossabet', 0),
  ('Novibet', 0),
  ('Obabet', 0),
  ('Onabet', 0),
  ('P9', 0),
  ('Pagbet', 0),
  ('Pagol', 0),
  ('Papigames', 0),
  ('Parimatch', 0),
  ('Pinnacle', 0),
  ('Pixbet', 0),
  ('Playbet', 0),
  ('Playpix', 0),
  ('Qgbet', 0),
  ('R7', 0),
  ('Reals Bet', 0),
  ('Rei do Pitaco', 0),
  ('Ricobet', 0),
  ('Rivalo', 0),
  ('Segurobet', 0),
  ('Seubet', 0),
  ('Sorte Online', 0),
  ('Sorte na Bet', 0),
  ('Sorteonline', 0),
  ('Spinbet', 0),
  ('Sportingbet', 0),
  ('Sportybet', 0),
  ('Stake', 0),
  ('Start Bet', 0),
  ('Superbet', 0),
  ('Supremabet', 0),
  ('Tivobet', 0),
  ('Ultrabet', 0),
  ('Upbet', 0),
  ('Ux Bet', 0),
  ('Vai de Bet', 0),
  ('Vbet', 0),
  ('Verabet', 0),
  ('Versus', 0),
  ('Vert Bet', 0),
  ('Viabet', 0),
  ('Vivasorte', 0),
  ('Vupi Bet', 0),
  ('Wjcasino', 0)

ON CONFLICT (nome) DO NOTHING;