ALTER TABLE IF EXISTS procedimentos_entradas
  ADD COLUMN IF NOT EXISTS aumento_percentual DOUBLE PRECISION NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS cashback_percentual DOUBLE PRECISION NOT NULL DEFAULT 0;
